### ISSUE TITLE
How can i add custom link to context menu?

### ISSUE THREAD

**Issue by mahmutbayri** [hola/videojs5-settings#1]
Hi,

I would like to add a menu item to context menu like "Copy embed url, Copy video page url" via player options.  How could it be possible?

Thanks.

**Comment by akashta** [comment]
Hi,

I'm going to add this in the next hola player version. Could you please clarify, how "Copy embed url" is supposed to work?
As I understand, by "embed url" you mean the iframe url and "video page url" is the top frame url. If so, do you need both items in the same time or add an option to choose which url should be copied?

Also we want to add a menu item to copy video page url with current position (will add url param `#t=<start time>`).

**Comment by akashta** [comment]
Implemented in Hola player 1.0.84.
To activate "Copy embed code" menu item need to init player with `embed_code` options: `window.hola_player({embed_code: '<some code>'});`
