### ISSUE TITLE
InfoOverlay leak/nullref on dispose

### ISSUE THREAD

**Issue by ghost** [hola/videojs5-settings#3]
When disposing a player, the interval updating InfoOverlay is not cleared, leading to an exception every second for a null reference on `currentTime`

In the constructor, add:

```js
this.updateInterval = null;
```

replace the setInterval with:

```js
this.updateInterval = setInterval(function(){ _this.update(); }, 1000);
```

add a dispose handler to the component:

```js
dispose: function() {
    if (this.updateInterval !== null) {
        clearInterval(this.updateInterval)
    }
}
```

**Comment by akashta** [comment]
Thank you for reporting the bug. Fixed.
